# TODAY'S CONCEPTS
## KNN (K Nearest Neighbhours)
### it is non linear classification algoruithm
<img src = "http://res.cloudinary.com/dyd911kmh/image/upload/f_auto,q_auto:best/v1531424125/KNN_final_a1mrv9.png
" width ="300px" length = "300px">
<img src = "http://res.cloudinary.com/dyd911kmh/image/upload/f_auto,q_auto:best/v1531424125/KNN_final1_ibdm8a.png" width ="500px" length = "500px">

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#getting the data
df =pd.read_csv("https://raw.githubusercontent.com/AP-State-Skill-Development-Corporation/Datasets/master/Classification/shirt.csv")

In [3]:
df

Height  Weight Size
0      158      58    M
1      158      59    M
2      158      63    M
3      160      59    M
4      160      60    M
5      163      60    M
6      163      61    M
7      160      64    L
8      163      64    L
9      165      61    L
10     165      61    L
11     165      62    L
12     168      62    L
13     168      63    L
14     168      66    L
15     170      63    L
16     170      64    L
17     170      68    L

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Height  18 non-null     int64 
 1   Weight  18 non-null     int64 
 2   Size    18 non-null     object
dtypes: int64(2), object(1)
memory usage: 560.0+ bytes


In [5]:
df.isnull().sum()

Height    0
Weight    0
Size      0
dtype: int64

In [6]:
df['Size'].value_counts()

L    11
M     7
Name: Size, dtype: int64

In [7]:
df.head()

Height  Weight Size
0     158      58    M
1     158      59    M
2     158      63    M
3     160      59    M
4     160      60    M

In [8]:
df.describe()

Height     Weight
count   18.00000  18.000000
mean   164.00000  62.111111
std      4.32503   2.564208
min    158.00000  58.000000
25%    160.00000  60.250000
50%    164.00000  62.000000
75%    168.00000  63.750000
max    170.00000  68.000000

In [9]:
inputdata = df[['Height','Weight']]
inputdata

Height  Weight
0      158      58
1      158      59
2      158      63
3      160      59
4      160      60
5      163      60
6      163      61
7      160      64
8      163      64
9      165      61
10     165      61
11     165      62
12     168      62
13     168      63
14     168      66
15     170      63
16     170      64
17     170      68

In [10]:
output = df['Size']
output

0     M
1     M
2     M
3     M
4     M
5     M
6     M
7     L
8     L
9     L
10    L
11    L
12    L
13    L
14    L
15    L
16    L
17    L
Name: Size, dtype: object

In [11]:
pd.get_dummies(output)

L  M
0   0  1
1   0  1
2   0  1
3   0  1
4   0  1
5   0  1
6   0  1
7   1  0
8   1  0
9   1  0
10  1  0
11  1  0
12  1  0
13  1  0
14  1  0
15  1  0
16  1  0
17  1  0

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
label = LabelEncoder()

In [14]:
data =  label.fit_transform(output)

In [15]:
data

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
df['Size'] = data
df['Size']

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
Name: Size, dtype: int32

In [17]:
output = df['Size']

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Height  18 non-null     int64
 1   Weight  18 non-null     int64
 2   Size    18 non-null     int32
dtypes: int32(1), int64(2)
memory usage: 488.0 bytes


In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
knn = KNeighborsClassifier(n_neighbors = 5)

In [21]:
knn.fit(inputdata,output)

KNeighborsClassifier()

In [22]:
#predict the model
pred = knn.predict(inputdata)

In [23]:
pred

array([1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [25]:
accuracy_score(output,pred)*100

83.33333333333334

In [26]:
confusion_matrix(output,pred) 

array([[10,  1],
       [ 2,  5]], dtype=int64)

In [27]:
print(classification_report(output,pred))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87        11
           1       0.83      0.71      0.77         7

    accuracy                           0.83        18
   macro avg       0.83      0.81      0.82        18
weighted avg       0.83      0.83      0.83        18



wine dataset appling in knn algorith 

In [28]:
data1 = pd.read_excel('winequality-red.xls')

In [29]:
data1

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1739            6.6              0.52         0.04             2.2      0.069   
1740            6.6              0.50         0.04             2.1      0.068   
1741            8.6              0.38         0.36             3.0      0.081   
1742            7.6              0.51         0.15             2.8      0.110   
1743            7.7              0.62         0.04             3.8      0.084   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0   0.9978  3.51       0.56   
1                    25.0                  67.0   0.9968  3.20       0.68   
2                    15.0                  54.0   0.9970  3.26       0.65   
3                    17.0                  60.0   0.9980  3.16       0.58   
4                    11.0                  34.0   0.9978  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1739                  8.0                  15.0   0.9956  3.40       0.63   
1740                  6.0                  14.0   0.9955  3.39       0.64   
1741                 30.0                 119.0   0.9970  3.20       0.56   
1742                 33.0                  73.0   0.9955  3.17       0.63   
1743                 25.0                  45.0   0.9978  3.34       0.53   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1739      9.4        6  
1740      9.4        6  
1741      9.4        5  
1742     10.2        6  
1743      9.5        5  

[1744 rows x 12 columns]

In [30]:
data1.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [31]:
data1['quality'].value_counts()

5    716
6    647
7    224
4     90
8     46
3     21
Name: quality, dtype: int64

In [32]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1744 entries, 0 to 1743
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1744 non-null   float64
 1   volatile acidity      1744 non-null   float64
 2   citric acid           1744 non-null   float64
 3   residual sugar        1744 non-null   float64
 4   chlorides             1744 non-null   float64
 5   free sulfur dioxide   1744 non-null   float64
 6   total sulfur dioxide  1744 non-null   float64
 7   density               1744 non-null   float64
 8   pH                    1744 non-null   float64
 9   sulphates             1744 non-null   float64
 10  alcohol               1744 non-null   float64
 11  quality               1744 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 163.6 KB


In [33]:
data1.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [34]:
inputdata = data1.drop(['quality'],axis = 1)
inputdata

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1739            6.6              0.52         0.04             2.2      0.069   
1740            6.6              0.50         0.04             2.1      0.068   
1741            8.6              0.38         0.36             3.0      0.081   
1742            7.6              0.51         0.15             2.8      0.110   
1743            7.7              0.62         0.04             3.8      0.084   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0   0.9978  3.51       0.56   
1                    25.0                  67.0   0.9968  3.20       0.68   
2                    15.0                  54.0   0.9970  3.26       0.65   
3                    17.0                  60.0   0.9980  3.16       0.58   
4                    11.0                  34.0   0.9978  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1739                  8.0                  15.0   0.9956  3.40       0.63   
1740                  6.0                  14.0   0.9955  3.39       0.64   
1741                 30.0                 119.0   0.9970  3.20       0.56   
1742                 33.0                  73.0   0.9955  3.17       0.63   
1743                 25.0                  45.0   0.9978  3.34       0.53   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1739      9.4  
1740      9.4  
1741      9.4  
1742     10.2  
1743      9.5  

[1744 rows x 11 columns]

In [35]:
inputdata.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [36]:
output = data1['quality']

In [37]:
output.head()

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

In [38]:
out = label.fit_transform(output)
out

array([2, 2, 2, ..., 2, 3, 2], dtype=int64)

In [39]:
data1['quality'] = out
out1 = data1['quality']
out1

0       2
1       2
2       2
3       3
4       2
       ..
1739    3
1740    3
1741    2
1742    3
1743    2
Name: quality, Length: 1744, dtype: int64

In [40]:
data1['quality'].value_counts()

2    716
3    647
4    224
1     90
5     46
0     21
Name: quality, dtype: int64

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
x_train,x_test,y_train,y_test = train_test_split(inputdata,out1,test_size = 0.3)

In [43]:
#appling the model
from sklearn.neighbors import KNeighborsClassifier

In [44]:
knn1 = KNeighborsClassifier(n_neighbors = 4)

In [45]:
knn1.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [47]:
pred = knn1.predict(x_test)
pred

array([3, 3, 4, 2, 2, 2, 2, 2, 3, 4, 3, 2, 2, 3, 2, 2, 3, 3, 4, 3, 3, 2,
       2, 2, 3, 2, 2, 2, 3, 2, 4, 3, 3, 2, 2, 2, 2, 4, 3, 2, 2, 2, 2, 3,
       2, 1, 2, 4, 4, 3, 2, 2, 4, 4, 2, 2, 2, 2, 3, 2, 2, 4, 3, 2, 3, 2,
       4, 2, 2, 3, 2, 3, 2, 4, 2, 2, 3, 3, 3, 3, 2, 3, 3, 2, 2, 5, 4, 2,
       2, 2, 2, 3, 5, 2, 2, 3, 2, 3, 2, 3, 2, 2, 3, 3, 2, 3, 4, 2, 0, 3,
       3, 2, 2, 1, 0, 2, 2, 1, 2, 2, 4, 3, 2, 4, 2, 3, 2, 2, 2, 2, 4, 2,
       5, 3, 2, 4, 2, 3, 3, 5, 3, 3, 3, 2, 3, 1, 3, 2, 2, 2, 1, 2, 2, 0,
       1, 3, 1, 3, 2, 3, 3, 4, 2, 3, 2, 3, 2, 3, 2, 3, 3, 4, 4, 3, 3, 2,
       3, 2, 3, 2, 2, 2, 4, 2, 2, 3, 1, 3, 3, 2, 1, 2, 2, 2, 2, 2, 3, 3,
       3, 2, 2, 2, 3, 2, 2, 4, 1, 2, 2, 4, 3, 2, 4, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 4, 2, 3, 3, 1, 5, 4, 3, 2, 3, 3, 2, 2, 4, 3, 2, 3, 3,
       2, 1, 4, 3, 0, 2, 2, 2, 3, 2, 3, 4, 2, 4, 1, 3, 2, 3, 0, 3, 2, 2,
       3, 3, 2, 3, 3, 3, 2, 2, 0, 3, 2, 4, 3, 3, 3, 2, 2, 3, 4, 3, 2, 4,
       3, 3, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3, 3, 4,

In [49]:
accuracy_score(y_test,pred)*100

59.16030534351145

In [51]:
confusion_matrix(y_test,pred)

array([[  5,   1,   0,   0,   0,   0],
       [  0,  14,  10,   5,   0,   0],
       [  1,   7, 164,  45,   5,   0],
       [  1,   2,  72,  91,  21,   1],
       [  0,   1,  15,  25,  29,   1],
       [  0,   0,   0,   0,   1,   7]], dtype=int64)